#!/bin/bash
set -e

echo "=== Vercel Build Script ==="
echo "PWD: $(pwd)"
echo "Creating .env at repo root..."

cat > .env << 'ENVEOF'
VITE_ZK_MAFIA_CONTRACT_ID=CDNAQVX6I4IAGMQAOPJOMH33G7XOTEHXC6ILDSKAS3ZMGGSHJXTH7VVA
VITE_MOCK_GAME_HUB_CONTRACT_ID=CB4VZAT2U3UC6XFK3N23SKRF2NDCMP3QHJYMCHHFMZO7MRQO6DQ2EMYG
VITE_SOROBAN_RPC_URL=https://soroban-testnet.stellar.org
VITE_NETWORK_PASSPHRASE=Test SDF Network ; September 2015
VITE_DEV_PLAYER1_ADDRESS=GCIFFUIDJNV65OOJGECFLCI7JZYICOY6N4ZDQKWHYEHV7RMJZBVKAPZZ
VITE_DEV_PLAYER2_ADDRESS=GACZHIIAKJNRIMRS3M26DKYJXEGIDO3T22AXNDW5HAFK7YTQ4E6NYCE4
VITE_DEV_PLAYER1_SECRET=SCCYPQBDAQ7OJKXEXF2YHQUXW3I3D77QBPP7EQVPISC6NBETKID2QACH
VITE_DEV_PLAYER2_SECRET=SBNDVIYVUGEI22W73B3E5NWKW3RSIQFQNIUEGGPZ5L3TZQD3VLEA25XI
ENVEOF

echo "=== .env contents ==="
cat .env
echo "=== End .env ==="

echo "Changing to zk-mafia-frontend..."
cd zk-mafia-frontend
echo "PWD after cd: $(pwd)"
echo "Parent dir contents:"
ls -la ../
echo "=== Installing deps ==="
bun install
echo "=== Building ==="
bun run build